# PRACTICAL 1:
Write a program to implement :
1. NumPy N-dimensional Array
2. Functions to Create Arrays
3. Combining Arrays

#NumPy N-dimensional Array
NumPy is a Python library that can be used for scientic and numerical applications and is the
tool to use for linear algebra operations. The main data structure in NumPy is the ndarray,
which is a shorthand name for N-dimensional array. When working with NumPy, data in an
ndarray is simply referred to as an array. It is a xed-sized array in memory that contains data
of the same type, such as integers or 
oating point values.
The data type supported by an array can be accessed via the dtype attribute on the array.
The dimensions of an array can be accessed via the shape attribute that returns a tuple
describing the length of each dimension. There are a host of other attributes. A simple way to create an array from data or simple Python data structures like a list is to use the array()
function. The example below creates a Python list of 3 
Floating point values, then creates an
ndarray from the list and access the arrays' shape and data type.

1.NumPy N-dimensional Array

In [ ]:
# create array
from numpy import array
# create array
l = [1.0, 2.0, 3.0]
a = array(l)
# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64




# Functions to Create Arrays

```



#Empty
The empty() function will create a new array of the specied shape. The argument to the
function is an array or tuple that species the length of each dimension of the array to create.
The values or content of the created array will be random and will need to be assigned before
use. The example below creates an empty 3  3 two-dimensional array.

In [ ]:
# create empty array
from numpy import empty
a = empty([3,3])
print(a)
print(a.dtype)

[[1.6016952e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]
float64


#Zeros
The zeros() function will create a new array of the specied size with the contents lled with
zero values. The argument to the function is an array or tuple that species the length of each
dimension of the array to create. The example below creates a 3  5 zero two-dimensional array.

In [ ]:
from numpy import array
# create empty array
from numpy import zeros
a = zeros([3,3])
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


#Ones
The ones() function will create a new array of the specied size with the contents lled with
one values. The argument to the function is an array or tuple that species the length of each
dimension of the array to create. The example below creates a 5-element one-dimensional array.

In [ ]:
from numpy import array
# create empty array
from numpy import ones
a = ones([3,3])
print(a)
print(a.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64


#Combining Arrays

#Vertical Stack
Given two or more existing arrays, you can stack them vertically using the vstack() function.
For example, given two one-dimensional arrays, you can create a new two-dimensional array
with two rows by vertically stacking them. This is demonstrated in the example below.

In [ ]:
# create array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


#Horizontal Stack
Given two or more existing arrays, you can stack them horizontally using the hstack() function.
For example, given two one-dimensional arrays, you can create a new one-dimensional array or
one row with the columns of the rst and second arrays concatenated. This is demonstrated in
the example below.

In [ ]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


#PRACTICAL 2:
Write a program to implement :
1. From List to Arrays
2. Array Indexing
3. Array Slicing
4. Array Reshaping

#From List to Arrays
In general, I recommend loading your data from le using Pandas or even NumPy functions.
This section assumes you have loaded or generated your data by other means and it is now
represented using Python lists. Let's look at converting your data in lists to NumPy arrays.

#From 1D LIST to Array:

#One-Dimensional List to Array
You may load your data or generate your data and have access to it as a list. You can convert a
one-dimensional list of data to an array by calling the array() NumPy function.

In [1]:


# create one-dimensional array
from numpy import array
# list of data
data = [11, 22, 33, 44, 55]
# array of data
data = array(data)
print(data)
print(type(data))





[11 22 33 44 55]
<class 'numpy.ndarray'>


#From 2D LIST  to Array:

#Two-Dimensional List of Lists to Array
It is more likely in machine learning that you will have two-dimensional data. That is a table of
data where each row represents a new observation and each column a new feature. Perhaps you
generated the data or loaded it using custom code and now you have a list of lists. Each list
represents a new observation. You can convert your list of lists to a NumPy array the same way
as above, by calling the array() function.

In [ ]:
# create two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


#One-Dimensional Indexing:

#Array Indexing
Once your data is represented using a NumPy array, you can access it using indexing. Let's
look at some examples of accessing data via indexing.

In [ ]:
# index a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])

11
55



Generally, indexing works just like you would expect from your experience with other programming
languages, like Java, C#, and C++. For example, you can access elements using the
bracket operator [] specifying the zero-oset index for the value to retrieve.

In [ ]:
# index array out of bounds
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[5])

IndexError: ignored

**Two-Dimensional Indexing:**

Indexing two-dimensional data is similar to indexing one-dimensional data, except that a comma
is used to separate the index for each dimension.

In [ ]:
# index two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,1])

22




#Two Dimensional Indexing





In [ ]:
# index row of two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,])

[11 22]


#Array Slicing:

Array Slicing
So far, so good; creating and indexing arrays looks familiar. Now we come to array slicing, and
this is one feature that causes problems for beginners to Python and NumPy arrays. Structures
like lists and NumPy arrays can be sliced. This means that a subsequence of the structure
can be indexed and retrieved. This is most useful in machine learning when specifying input
variables and output variables, or splitting training rows from testing rows. Slicing is specied
using the colon operator : with a from and to index before and after the column respectively.
The slice extends from the from index and ends one item before the to index.

In [ ]:


# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[2:])




[33 44 55]


Split Input and Output Features
It is common to split your loaded data into input variables (X) and the output variable (y). We
can do this by slicing all rows and all columns up to, but before the last column, then separately
indexing the last column. For the input features, we can select all rows and all columns except
the last one by specifying : for in the rows index, and :-1 in the columns index.

In [ ]:
# split input and output data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X, y = data[1:, :], data[:,:]
print(X)
print(y)

[[44 55 66]
 [77 88 99]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]


Split Train and Test Rows
It is common to split a loaded dataset into separate train and test sets. This is a splitting of
rows where some portion will be used to train the model and the remaining portion will be used
to estimate the skill of the trained model. This would involve slicing all columns by specifying :
in the second dimension index. The training dataset would be all rows from the beginning to
the split point.

In [ ]:
# split train and test data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


In [ ]:
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

Array Reshaping
After slicing your data, you may need to reshape it. For example, some libraries, such as
scikit-learn, may require that a one-dimensional array of output variables (y) be shaped as a
two-dimensional array with one column and outcomes for each column. Some algorithms, like
the Long Short-Term Memory recurrent neural network in Keras, require input to be specied
as a three-dimensional array comprised of samples, timesteps, and features. It is important to
know how to reshape your NumPy arrays so that your data meets the expectation of specic
Python libraries. We will look at these two examples.

#DATA SHAPE

In [ ]:
# shape of one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [ ]:
# shape of a two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)

(3, 2)


In [ ]:
# row and column shape of two-dimensional array
from numpy import array
# list of data
data = [[11, 22],[33, 44],
[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])
        

Rows: 3
Cols: 2


# ARRAY RESHAPING 1D ARRAY TO 2D ARRAY


Reshape 1D to 2D Array
It is common to need to reshape a one-dimensional array into a two-dimensional array with
one column and multiple arrays. NumPy provides the reshape() function on the NumPy array
object that can be used to reshape the data. The reshape() function takes a single argument
that species the new shape of the array. In the case of reshaping a one-dimensional array into
a two-dimensional array with one column, the tuple would be the shape of the array as the rst
dimension (data.shape[0]) and 1 for the second dimension.

In [ ]:
# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)

(5,)
(5, 1)


# ARRAY RESHAPING 2D ARRAY TO 3D ARRAY

Reshape 2D to 3D Array
It is common to need to reshape two-dimensional data where each row represents a sequence
into a three-dimensional array for algorithms that expect multiple samples of one or more time
steps and one or more features. A good example is the LSTM recurrent neural network model
in the Keras deep learning library. The reshape function can be used directly, specifying the
new dimensionality. This is clear with an example where each sequence has multiple time steps
with one observation (feature) at each time step. We can use the sizes in the shape attribute on
the array to specify the number of samples (rows) and columns (time steps) and x the number
of features at 1.

In [ ]:

from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)


#PRACTICAL 3:
Write a program to implement :
1. Vector Arithmetic
2. Vector Dot Product
3. Vector-Scalar Multiplication

A vector is a tuple of one or more values called scalars.
Vectors are built from components, which are ordinary numbers. You can think of
a vector as a list of numbers, and vector algebra as operations performed on the
numbers in the list.Vectors are often represented using a lowercase character such as v; for example:
v = (v1; v2; v3) 
Where v1, v2, v3 are scalar values, often real values.
Vectors are also shown using a vertical representation or a column; for example:
v =( v1 v2 v3)

It is common to represent the target variable as a vector with the lowercase y when describing
the training of a machine learning algorithm. It is common to introduce vectors using a geometric
analogy, where a vector represents a point or coordinate in an n-dimensional space, where n
is the number of dimensions, such as 2. The vector can also be thought of as a line from the
origin of the vector space with a direction and a magnitude.
These analogies are good as a starting point, but should not be held too tightly as we often
consider very high dimensional vectors in machine learning. I nd the vector-as-coordinate the
most compelling analogy in machine learning. Now that we know what a vector is, let's look at
how to dene a vector in Python.

#Defining a Vector
We can represent a vector in Python as a NumPy array. A NumPy array can be created from
a list of numbers. For example, below we dene a vector with the length of 3 and the integer
values 1, 2 and 3.

In [ ]:
# create a vector
from numpy import array
# define vector
v = array([1, 2, 3])
print(v)

[1 2 3]


#Vector Arithmetic
In this section will demonstrate simple vector-vector arithmetic, where all operations are
performed element-wise between two vectors of equal length to result in a new vector with the
same length

#Vector Addition
Two vectors of equal length can be added together to create a new third vector.
c = a + b (7.3)
The new vector has the same length as the other two vectors. Each element of the new
vector is calculated as the addition of the elements of the other vectors at the same index; for
example:
c = (a1 + b1; a2 + b2; a3 + b3)

In [ ]:
# vector addition
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# add vectors
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


#Vector Subtraction
One vector can be subtracted from another vector of equal length to create a new third vector.
c = a - b (7.6)
7.4. Vector Arithmetic 47
As with addition, the new vector has the same length as the parent vectors and each element
of the new vector is calculated as the subtraction of the elements at the same indices.
c = (a1 - b1; a2 - b2; a3 - b3)

In [ ]:
# vector subtraction
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([0.5, 0.5, 0.5])
print(b)
# subtract vectors
c = a - b
print(c)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


#Vector Multiplication
Two vectors of equal length can be multiplied together.
c = a * b (7.9)
As with addition and subtraction, this operation is performed element-wise to result in a
new vector of the same length.
c = (a1* b1; a2 * b2; a3 * b3) 
or
c = (a1b1; a2b2; a3b3)

In [ ]:
# vector multiplication
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


#Vector Division
Two vectors of equal length can be divided.
c =a/b

As with other arithmetic operations, this operation is performed element-wise to result in a
new vector of the same length.
c = (a1/b1;a2/b2;a3/b3)

In [ ]:
# vector division
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# divide vectors
c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


#Vector Dot Product
We can calculate the sum of the multiplied elements of two vectors of the same length to give a
scalar. This is called the dot product, named because of the dot operator used when describing
the operation.
The dot product is the key tool for calculating vector projections, vector decompositions,
and determining orthogonality. The name dot product comes from the symbol
used to denote it

In [ ]:
# vector dot product
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


#Vector-Scalar Multiplication
A vector can be multiplied by a scalar, in eect scaling the magnitude of the vector. To keep
notation simple, we will use lowercase s to represent the scalar value.
c = s * v (7.19)
or
c = sv (7.20)
The multiplication is performed on each element of the vector to result in a new scaled
vector of the same length.
c = (s * v1; s * v2; s * v3)

In [ ]:
# vector-scalar multiplication
from numpy import array
# define vector
a = array([1, 2, 3])
print(a)
# define scalar
s = 0.5
print(s)
# multiplication
c = s * a
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]


#PRACTICAL 4:
Write a program to implement :
1. Vector Norm
2. Vector L1 Norm
3. Vector L2 Norm
4. Vector Max Norm


#Vector Norm
Calculating the size or length of a vector is often required either directly or as part of a broader
vector or vector-matrix operation. The length of the vector is referred to as the vector norm or
the vector's magnitude.
The length of a vector is a nonnegative number that describes the extent of the
vector in space, and is sometimes referred to as the vector's magnitude or the norm.The length of the vector is always a positive number, except for a vector of all zero values.
It is calculated using some measure that summarizes the distance of the vector from the origin
of the vector space. For example, the origin of a vector space for a vector with 3 elements is
(0; 0; 0). Notations are used to represent the vector norm in broader calculations and the type
of vector norm calculation almost always has its own unique notation. We will take a look at a
few common vector norm calculations used in machine learning.

#Vector L1 Norm
The length of a vector can be calculated using the L1 norm, where the 1 is a superscript of
the L. The notation for the L1 norm of a vector is jjvjj1, where 1 is a subscript. As such, this
length is sometimes called the taxicab norm or the Manhattan norm.
L1(v) = ||v||1
The L1 norm is calculated as the sum of the absolute vector values, where the absolute value
of a scalar uses the notation ja1j. In eect, the norm is a calculation of the Manhattan distance
from the origin of the vector space.
||v||1 = |a1| + |a2| + |a3| 
In several machine learning applications, it is important to discriminate between
elements that are exactly zero and elements that are small but nonzero. In these
cases, we turn to a function that grows at the same rate in all locations, but retains
mathematical simplicity: the L1 norm.

In [ ]:
# vector L1 norm
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
l1 = norm(a, 1)
print(l1)

[1 2 3]
6.0


#Vector L2 Norm
The length of a vector can be calculated using the L2 norm, where the 2 is a superscript of the
L. The notation for the L2 norm of a vector is jjvjj2 where 2 is a subscript.
L2(v) = ||v||2 
The L2 norm calculates the distance of the vector coordinate from the origin of the vector
space. As such, it is also known as the Euclidean norm as it is calculated as the Euclidean
distance from the origin. The result is a positive distance value. The L2 norm is calculated as
the square root of the sum of the squared vector values.
||v||2 =sqrt(a1**2+a2**2+a3**2)
The L2 norm of a vector can be calculated in NumPy using the norm() function with default
parameters.

#Vector Max Norm
The length of a vector can be calculated using the maximum norm, also called max norm. Max
norm of a vector is referred to as Linf where inf is a superscript and can be represented with the infinity symbol. The notation for max norm is jjvjjinf , where inf is a subscript.
Linf (v) = ||v||inf 
The max norm is calculated as returning the maximum value of the vector, hence the name.
||v||inf = max a1; a2; a3 
The max norm of a vector can be calculated in NumPy using the norm() function with the
order parameter set to inf.

In [ ]:
# vector max norm
from math import inf
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
maxnorm = norm(a, inf)
print(maxnorm)

[1 2 3]
3.0


#PRACTICAL 5:
Write a program to implement :
1. Square Matrix
2. Symmetric Matrix
3. Triangular Matrix
4. Diagonal Matrix
5. Identity Matrix
6. Orthogonal Matrix


#Square Matrix
A square matrix is a matrix where the number of rows (n) is equivalent to the number of
columns (m).
n  m (10.1)
The square matrix is contrasted with the rectangular matrix where the number of rows and
columns are not equal. Given that the number of rows and columns match, the dimensions are
usually denoted as n, e.g. nn. The size of the matrix is called the order, so an order 4 square
matrix is 4  4. The vector of values along the diagonal of the matrix from the top left to the
bottom right is called the main diagonal. Below is an example of an order 3 square matrix.
M =(1 2 3;1 2 3;1 2 3)

Square matrices are readily added and multiplied together and are the basis of many simple
linear transformations, such as rotations (as in the rotations of images).

#Symmetric Matrix
A symmetric matrix is a type of square matrix where the top-right triangle is the same as the
bottom-left triangle.
It is no exaggeration to say that symmetric matrices S are the most important
matrices the world will ever see | in the theory of linear algebra and also in the
applications.
| Page 338, Introduction to Linear Algebra, Fifth Edition, 2016.
To be symmetric, the axis of symmetry is always the main diagonal of the matrix, from the
top left to the bottom right. Below is an example of a 5  5 symmetric matrix.
M =(
1 2 3 4 5;
2 1 2 3 4;
3 2 1 2 3;
4 3 2 1 2;
5 4 3 2 1;
)
A symmetric matrix is always square and equal to its own transpose. The transpose is an
operation that 
ips the number of rows and columns. It is explained in more detail in the next
lesson.
M = MT

#Triangular Matrix
A triangular matrix is a type of square matrix that has all values in the upper-right or lower-left
of the matrix with the remaining elements lled with zero values. A triangular matrix with
values only above the main diagonal is called an upper triangular matrix. Whereas, a triangular
matrix with values only below the main diagonal is called a lower triangular matrix. Below is
an example of a 3  3 upper triangular matrix.
M =
[
1 2 3;
0 2 3;
0 0 3;
]
Below is an example of a 3  3 lower triangular matrix.
M =[
1 0 0;
1 2 0;
1 2 3]
A (10.6)
NumPy provides functions to calculate a triangular matrix from an existing square matrix.
The tril() function to calculate the lower triangular matrix from a given matrix and the
triu() to calculate the upper triangular matrix from a given matrix The example below denes
a 3  3 square matrix and calculates the lower and upper triangular matrix from it.

In [ ]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# lower triangular matrix
lower = tril(M)
print(lower)
# upper triangular matrix
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


#Diagonal Matrix
A diagonal matrix is one where values outside of the main diagonal have a zero value, where the
main diagonal is taken from the top left of the matrix to the bottom right. A diagonal matrix
is often denoted with the variable D and may be represented as a full matrix or as a vector of
values on the main diagonal.
Diagonal matrices consist mostly of zeros and have non-zero entries only along the
main diagonal.

In [ ]:
# diagonal matrix
from numpy import array
from numpy import diag
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# extract diagonal vector
d = diag(M)
print(d)
# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


#Identity Matrix
An identity matrix is a square matrix that does not change a vector when multiplied. The
values of an identity matrix are known. All of the scalar values along the main diagonal (top-left
to bottom-right) have the value one, while all other values are zero.
An identity matrix is a matrix that does not change any vector when we multiply
that vector by that matrix.

In [ ]:
# identity matrix
from numpy import identity
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#Orthogonal Matrix
Two vectors are orthogonal when their dot product equals zero. The length of each vector is 1
then the vectors are called orthonormal because they are both orthogonal and normalized.

In [ ]:
# orthogonal matrix
from numpy import array
from numpy.linalg import inv
# define orthogonal matrix
Q = array([
[1, 0],
[0, -1]])
print(Q)
# inverse equivalence
V = inv(Q)
print(Q.T)
print(V)
# identity equivalence
I = Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]


#PRACTICAL 6:
Write a program to implement :
1. Transpose
2. Inverse
3. Trace
4. Determinant
5. Rank

#A defined matrix can be transposed, which creates a new matrix with the number of columns
and rows 
ipped. This is denoted by the superscript T next to the matrix AT .
C = AT

In [ ]:
# transpose matrix
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# calculate transpose
C = A.T
print(C)

#Inverse
Matrix inversion is a process that nds another matrix that when multiplied with the matrix,
results in an identity matrix. Given a matrix A, nd matrix B, such that AB = In or BA = In.
AB = BA = In

In [ ]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[1.0, 2.0],
[3.0, 4.0]])
print(A)
# invert matrix
B = inv(A)
print(B)
# multiply A and B
I = A.dot(B)
print(I)

#Trace
A trace of a square matrix is the sum of the values on the main diagonal of the matrix (top-left
to bottom-right).
The trace operator gives the sum of all of the diagonal entries of a matrix
| Page 46, Deep Learning, 2016.
The operation of calculating a trace on a square matrix is described using the notation tr(A)
where A is the square matrix on which the operation is being performed.
tr(A) 
The trace is calculated as the sum of the diagonal values; for example, in the case of a 3 * 3
matrix:
tr(A) = a1;1 + a2;2 + a3;3 (11.7)
Or, using array notation:
tr(A) = A[0; 0] + A[1; 1] + A[2; 2] 
We can calculate the trace of a matrix in NumPy using the trace() function.

In [ ]:
# matrix trace
from numpy import array
from numpy import trace
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# calculate trace
B = trace(A)
print(B)

#Determinant
The determinant of a square matrix is a scalar representation of the volume of the matrix.
The determinant describes the relative geometry of the vectors that make up the
rows of the matrix. More specically, the determinant of a matrix A tells you the
volume of a box with sides given by rows of A.

In [ ]:
# matrix determinant
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# calculate determinant
B = det(A)
print(B)

#Rank
The rank of a matrix is the estimate of the number of linearly independent rows or columns in
a matrix. The rank of a matrix M is often denoted as the function rank().
rank(A) (11.10)
An intuition for rank is to consider it the number of dimensions spanned by all of the vectors
within a matrix. For example, a rank of 0 suggest all vectors span a point, a rank of 1 suggests
all vectors span a line, a rank of 2 suggests all vectors span a two-dimensional plane. The rank
is estimated numerically, often using a matrix decomposition method. A common approach is to
use the Singular-Value Decomposition or SVD for short. NumPy provides the matrix rank()
function for calculating the rank of an array. It uses the SVD method to estimate the rank. The
example below demonstrates calculating the rank of a matrix with scalar values and another
vector with all zero values.

In [ ]:
# vector rank
from numpy import array
from numpy.linalg import matrix_rank
# rank
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

In [ ]:
# matrix rank
from numpy import array
from numpy.linalg import matrix_rank
# rank 0
M0 = array([
[0,0],
[0,0]])
print(M0)
mr0 = matrix_rank(M0)
print(mr0)
# rank 1
M1 = array([
[1,2],
[1,2]])
print(M1)
mr1 = matrix_rank(M1)
print(mr1)
# rank 2
M2 = array([
[1,2],
[3,4]])
print(M2)
mr2 = matrix_rank(M2)
print(mr2)

#PRACTICAL 7:
Write a program to implement :
1. Matrix-Matrix Multiplication
2. Matrix-Vector Multiplication
3. Matrix-Scalar Multiplication

#Matrix-Matrix Multiplication
Matrix multiplication, also called the matrix dot product is more complicated than the previous
operations and involves a rule as not all matrices can be multiplied together.
C = A · B (9.15)
or
C = AB (9.16)
The rule for matrix multiplication is as follows:
ˆ The number of columns (n) in the first matrix (A) must equal the number of rows (m) in
the second matrix (B).
For example, matrix A has the dimensions m rows and n columns and matrix B has the
dimensions n and k. The n columns in A and n rows in B are equal. The result is a new matrix
with m rows and k columns.
C(m, k) = A(m, n) · B(n, k) (9.17)
This rule applies for a chain of matrix multiplications where the number of columns in one
matrix in the chain must match the number of rows in the following matrix in the chain.
One of the most important operations involving matrices is multiplication of two
matrices. The matrix product of matrices A and B is a third matrix C. In order for
this product to be defined, A must have the same number of columns as B has rows.
If A is of shape m × n and B is of shape n × p, then C is of shape m × p.


In [ ]:
# matrix dot product
from numpy import array
# define first matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define second matrix
B = array([
[1, 2],
[3, 4]])
print(B)
# multiply matrices
C = A.dot(B)
print(C)
# multiply matrices with @ operator
D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


#Matrix-Vector Multiplication
A matrix and a vector can be multiplied together as long as the rule of matrix multiplication
is observed. Specifically, that the number of columns in the matrix must equal the number of
items in the vector. As with matrix multiplication, the operation can be written using the dot
notation. Because the vector only has one column, the result is always a vector.
c = A · v (9.22)
Or without the dot in a compact form.
c = Av (9.23)
The result is a vector with the same number of rows as the parent matrix.
A =


a1,1 a1,2
a2,1 a2,2
a3,1 a3,2

 (9.24)
v =

v1
v2

(9.25)
c =


a1,1 × v1 + a1,2 × v2
a2,1 × v1 + a2,2 × v2
a3,1 × v1 + a3,2 × v2

 (9.26)
9.7. Matrix-Scalar Multiplicat

In [ ]:
# matrix-vector multiplication
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define vector
B = array([0.5, 0.5])
print(B)
# multiply
C = A.dot(B)
print(C)


[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]


#Matrix-Scalar Multiplication
A matrix can be multiplied by a scalar. This can be represented using the dot notation between
the matrix and the scalar.
C = A · b (9.29)
9.7. Matrix-Scalar Multiplication 68
Or without the dot notation.
C = Ab (9.30)
The result is a matrix with the same size as the parent matrix where each element of the
matrix is multiplied by the scalar value.
A =


a1,1 a1,2
a2,1 a2,2
a3,1 a3,2

 (9.31)
C =


a1,1 × b + a1,2 × b
a2,1 × b + a2,2 × b
a3,1 × b + a3,2 × b

 (9.32)
or
C =


a1,1b + a1,2b
a2,1b + a2,2b
a3,1b + a3,2b

 (9.33)
We can also represent this with array notation.
C[0, 0] = A[0, 0] × b
C[1, 0] = A[1, 0] × b
C[2, 0] = A[2, 0] × b
C[0, 1] = A[0, 1] × b
C[1, 1] = A[1, 1] × b
C[2, 1] = A[2, 1] × b
(9.34)
This can be implemented directly in NumPy with the multiplication operator

In [ ]:
# matrix-scalar multiplication
from numpy import array
# define matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# define scalar
b = 0.5
print(b)
# multiply
C = A * b
print(C)


[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


1. Eigendecomposition of a Matrix
2. Eigenvectors and Eigenvalues
3. Calculation of Eigendecomposition
4. Confirm an Eigenvector and Eigenvalue
5. Reconstruct Matrix

Eigendecomposition of a Matrix
Eigendecomposition of a matrix is a type of decomposition that involves decomposing a square
matrix into a set of eigenvectors and eigenvalues.
One of the most widely used kinds of matrix decomposition is called eigendecomposition, in which we decompose a matrix into a set of eigenvectors and eigenvalues.

A vector is an eigenvector of a matrix if it satisfies the following equation.
A · v = λ · v 
This is called the eigenvalue equation, where A is the parent square matrix that we are
decomposing, v is the eigenvector of the matrix, and λ is the lowercase Greek letter lambda and
represents the eigenvalue scalar. Or without the dot notation.
Av = λv 
A matrix could have one eigenvector and eigenvalue for each dimension of the parent matrix.
Not all square matrices can be decomposed into eigenvectors and eigenvalues, and some can
only be decomposed in a way that requires complex numbers. The parent matrix can be shown
to be a product of the eigenvectors and eigenvalues.
A = Q · Λ · Q
T

Or, without the dot notation.
A = QΛQ
T

Where Q is a matrix comprised of the eigenvectors, Λ is the uppercase Greek letter lambda
and is the diagonal matrix comprised of the eigenvalues, and QT
is the transpose of the matrix
comprised of the eigenvectors.
However, we often want to decompose matrices into their eigenvalues and eigenvectors.
Doing so can help us to analyze certain properties of the matrix, much as decomposing
an integer into its prime factors can help us understand the behavior of that integer.

#Eigenvectors and Eigenvalues
Eigenvectors are unit vectors, which means that their length or magnitude is equal to 1.0. They
are often referred as right vectors, which simply means a column vector (as opposed to a row
vector or a left vector). A right-vector is a vector as we understand them. Eigenvalues are
coefficients applied to eigenvectors that give the vectors their length or magnitude. For example,
a negative eigenvalue may reverse the direction of the eigenvector as part of scaling it. A matrix
that has only positive eigenvalues is referred to as a positive definite matrix, whereas if the
eigenvalues are all negative, it is referred to as a negative definite matrix.
Decomposing a matrix in terms of its eigenvalues and its eigenvectors gives valuable
insights into the properties of the matrix. Certain matrix calculations, like computing
the power of the matrix, become much easier when we use the eigendecomposition
of the matrix

#Calculation of Eigendecomposition
An eigendecomposition is calculated on a square matrix using an efficient iterative algorithm, of
which we will not go into the details. Often an eigenvalue is found first, then an eigenvector is
found to solve the equation as a set of coefficients. The eigendecomposition can be calculated in
NumPy using the eig() function. The example below first defines a 3 × 3 square matrix. The
eigendecomposition is calculated on the matrix returning the eigenvalues and eigenvectors.

In [ ]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
print(values)
print(vectors)

#Confirm an Eigenvector and Eigenvalue
We can confirm that a vector is indeed an eigenvector of a matrix. We do this by multiplying
the candidate eigenvector by the value vector and comparing the result with the eigenvalue.
First, we will define a matrix, then calculate the eigenvalues and eigenvectors. We will then test
whether the first vector and value are in fact an eigenvalue and eigenvector for the matrix. We
know they are, but it is a good exercise.
The eigenvectors are returned as a matrix with the same dimensions as the parent matrix,
where each column is an eigenvector, e.g. the first eigenvector is vectors[:, 0]. Eigenvalues
are returned as a list, where value indices in the returned array are paired with eigenvectors
by column index, e.g. the first eigenvalue at values[0] is paired with the first eigenvector at
vectors[:, 0].


In [ ]:
# confirm eigenvector
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# factorize
values, vectors = eig(A)
# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(B)
C = vectors[:, 0] * values[0]
print(C)


#Reconstruct Matrix
We can reverse the process and reconstruct the original matrix given only the eigenvectors and
eigenvalues. First, the list of eigenvectors must be taken together as a matrix, where each vector
becomes a row. The eigenvalues need to be arranged into a diagonal matrix. The NumPy
diag() function can be used for this. Next, we need to calculate the inverse of the eigenvector
matrix, which we can achieve with the inv() NumPy function. Finally, these elements need to
be multiplied together with the dot() function.


In [ ]:
# reconstruct matrix
from numpy import diag
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = diag(values)
# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

#What is the Singular-Value Decomposition
2. Calculate Singular-Value Decomposition
3. Reconstruct Matrix
4. Pseudoinverse
5. Dimensionality Reduction

The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for
reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations
simpler. For the case of simplicity we will focus on the SVD for real-valued matrices and ignore
the case for complex numbers.
A = U · Σ · V
T
(16.1)
Where A is the real n × m matrix that we wish to decompose, U is an m × m matrix, Σ
represented by the uppercase Greek letter sigma) is an m × n diagonal matrix, and V
T
is the V
transpose of an n × n matrix where T is a superscript.
The Singular Value Decomposition is a highlight of linear algebra.
— Page 371, Introduction to Linear Algebra, 2016.
The diagonal values in the Σ matrix are known as the singular values of the original matrix
A. The columns of the U matrix are called the left-singular vectors of A, and the columns
of V are called the right-singular vectors of A. The SVD is calculated via iterative numerical
methods. We will not go into the details of these methods. Every rectangular matrix has a
singular value decomposition, although the resulting matrices may contain complex numbers
and the limitations of floating point arithmetic may cause some matrices to fail to decompose
neatly.
The singular value decomposition (SVD) provides another way to factorize a matrix,
into singular vectors and singular values. The SVD allows us to discover some of
the same kind of information as the eigendecomposition. However, the SVD is more
generally applicable.
— Pages 44-45, Deep Learning, 2016.
The SVD is used widely both in the calculation of other matrix operations, such as matrix
inverse, but also as a data reduction method in machine learning. SVD can also be used in least
squares linear regression, image compression, and denoising data.
The singular value decomposition (SVD) has numerous applications in statistics,
machine learning, and computer science. Applying the SVD to a matrix is like
looking inside it with X-ray vision...

#Calculate Singular-Value Decomposition
The SVD can be calculated by calling the svd() function. The function takes a matrix and
returns the U, Σ and V
T
elements. The Σ diagonal matrix is returned as a vector of singular
values. The V matrix is returned in a transposed form, e.g. V
T
. The example below defines a
3 × 2 matrix and calculates the singular-value decomposition.

In [ ]:
# singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

In [ ]:
# LU decomposition
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
P, L, U = lu(A)
print(P)
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)
print(B)


# Practice Questions:

1 Import numpy as np and print the version number.

In [ ]:
import numpy as np
print(np.__version__)

1.17.4


2 Create a 1D array of numbers from 0 to 9

In [ ]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3 Create a 3×3 numpy array of all True’s

In [ ]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4 Extract all odd numbers from arr

In [ ]:
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

5 Replace all odd numbers in arr with -1

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6 Q. Get the common items between a and b

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

7 How to remove from one array those items that exist in another?

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

8 How to get the positions where elements of two arrays match?

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

9 How to extract all numbers between a given range from a numpy array?

In [ ]:
 a= np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]




In [ ]:
# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]


In [ ]:

# Method 3:
a[(a >= 5) & (a <= 10)]