Practical 1

In [1]:
# create array
from numpy import array
# create array
l = [1.0, 2.0, 3.0]
a = array(l)
# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [2]:
# create empty array
from numpy import empty
a = empty([3,3])
print(a)
print(a.dtype)

[[2.42533822e-316 1.77863633e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 1.86989123e-051]
 [7.48417005e-067 4.46729011e-090 7.79505248e-043]]
float64


In [3]:
from numpy import array
# create empty array
from numpy import zeros
a = zeros([3,3])
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


In [4]:
from numpy import array
# create empty array
from numpy import ones
a = ones([3,3])
print(a)
print(a.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64


In [5]:
# create array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


Practical 2

In [7]:
# create one-dimensional array
from numpy import array
# list of data
data = [11, 22, 33, 44, 55]
# array of data
data = array(data)
print(data)
print(type(data))



[11 22 33 44 55]
<class 'numpy.ndarray'>
